### ISSUE TITLE
Error running Llama2 example on AMD Ryzen 7 8845HS

### ISSUE THREAD

**Issue by redpanda1829** [amd/RyzenAI-SW#108]
Hi,

I am trying to run the llama2 example and have followed the transformers example setup. However, the ctypes module which qlinear is dependent on is giving a FileNotFoundError 

```
Traceback (most recent call last):
...
File "C:\Users\...\RyzenAI-SW\example\transformers\third_party\_ffi\base.py", line 64, in _load_lib
    lib = ctypes.CDLL(lib_path[0], ctypes.RTLD_GLOBAL)
  File "C:\Users\...\anaconda3\envs\ryzenai-transformers\lib\ctypes\__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'C:\Users\...\RyzenAI-SW\example\transformers\third_party\lib\tvm_ipu.dll' (or one of its dependencies). Try using the full path with constructor syntax.
```
I have confirmed that the tvm_ipu DLL file is present.

My configurations are as below:
1. Driver - AMD Ryzen 7 8845HS
2. OS - Windows 11
3. Using Microsoft (R) C/C++ Optimizing Compiler Version 19.29.30154 for x64

**Comment by uday610** [comment]
In which step you getting this error? Are you following this page starting from Step 1?

https://github.com/amd/RyzenAI-SW/tree/main/example/transformers 

Also this version requires Visual Studio 2019 "Desktop development with C++" package for Step 3 "Build dependencies" 

We are going to release new version very soon that will require Visual Studio 2022.

**Comment by redpanda1829** [comment]
I have followed through from step 1 (download repo) to step 3 (build dependencies) and am only getting an error when I ran `python run_awq.py --w_bit 4 --task quantize`. The error occurred when importing qlinear.

I've also installed the "Desktop development with C++" package with Visual Studio 2019 Enterprise. Will await the new version in the meantime.

**Comment by uday610** [comment]
Your error is very odd because this llama2 flow was published in February month. I know many people have already tried it, and everything worked for them by following the steps, but I had not heard about this error before. 

Having said that 

Are you using Conda CMD prompt (not Powershell)? 

Did your step 3 (pip install ops\cpp --force-reinstall) was successful? 

If the above two are correct, can you try installing this in your conda environment? This is just a suggestion without knowing it will solve the issue or not 

conda install -c conda-forge cffi

**Comment by uday610** [comment]
You can try the above what I suggested.. Otherwise you might look into the current "main" branch where we published the new flow. I am closing this issue now
