### ISSUE TITLE
Slow performance using the opt-1.3b/opt-onnx example 

### ISSUE THREAD

**Issue by Robbson** [amd/RyzenAI-SW#14]
Hello,

after I couldn't use Ryzen AI on my Lenovo I got back to my Minisforum UM790 Pro where Ryzen AI is fortunately available on its 7940HS. 

Your new examples are a great starting point. I also appreciate the updated docs as well as the easier installation using a simple script (except that VS2019 is now a requirement).

I followed all steps for using the [opt-1.3b/opt-onnx](https://github.com/amd/RyzenAI-SW/tree/main/example/opt-1.3b/opt-onnx) to transform, optimize and quantize the model.

Afterwards, the execution on the CPU target runs fine, the loading time and warm up phase are pretty fast and including the test prompts it only took 15 seconds to complete on my machine.

Then, I tried the IPU version. It took much longer:
- Loading/Compiling time (or whatever that is what happens before the warm-up message appears): 85s
- Completion of all test prompts: 60s

So all in all it took nearly 2.5 minutes to complete.
Did I make a major mistake in the setup or something? Or is it a driver issue?
I also tried the other Runtime IPU Binary but it doesn't make a difference.

_Btw. I ran the none-quantized model (the output from SmoothQuant) just for fun on the CPU target and it's only 10 seconds slower than the quantized one._

**Comment by savitha-srinivasan** [comment]
Hi @Robbson, 

Thank you for trying out our examples. 

This is an early-access release to demonstrate the functionality of the flow to run large language models on the IPU. We will make sure to publish performance information (such as tokens generated per second) in subsequent releases.

The loading/preprocessing latency you see is a one-time overhead that stores quantized weights and fused operations in the cache (C:\<user>\temp\vaip\.cache). Once this is done this overhead should not be seen in subsequent runs.

To estimate the performance, it might be better to measure the time taken for the text generation/decoding process alone. Since this is also the most power-hungry process for the CPU, using the IPU is beneficial.

Note that the only IPU binary that can be used for this example is the one set in setup_onnx.bat. No other binary can be used.

**Comment by uday610** [comment]
closed as replied
