### ISSUE TITLE
tvm_ipu.dll loading error when running the transformer examples

### ISSUE THREAD

**Issue by luochenchi** [amd/RyzenAI-SW#54]
When running the transformer examples, I encounter the following error:

self._handle = _dlopen(self._name, mode)
OSError: [WinError 193] %1 is not a valid Win32 application

A window pops up saying that tvm_ipu.dll is either not designed to run on windows or it contains error. Error status: 0xc000012f.

Anyone know the solution to make it running?

**Comment by uday610** [comment]
Hi @luochenchi , we are now in the new release process, so the "main" branch might not be working for you for that reason. I can let you know when the "main" branch should work for you with the new software version. 

But for now, assuming you are using the published 1.0.1 release, you should clone the repo from the 1.0 branch (https://github.com/amd/RyzenAI-SW/tree/1.0) and start everything from the beginning (like starting a new conda environment). Please ensure to remove all the artifacts that you cloned (downloaded) from the "main" branch because that can cause the issue.

**Comment by luochenchi** [comment]
I used the latest release and the error then comes:

 File "C:\ProgramData\anaconda3\envs\ryzenai-1.0-transformers\lib\ctypes\__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'D:\RyzenAI-SW-1.0\example\transformers\third_party\lib\tvm_ipu.dll' (or one of its dependencies). Try using the full path with constructor syntax.

tvm_ipu.dll 's path is correct.

**Comment by uday610** [comment]
Hi @luochenchi ,
Delete your existing conda environment, 

`conda remove --name ENV_NAME --all`

Also, delete your cloned RyzenAI-SW folder. 

Clone from the 1.0 branch
`git clone https://github.com/amd/RyzenAI-SW.git -b 1.0`

And start following the instructions from the 1.0 branch only: https://github.com/amd/RyzenAI-SW/tree/1.0

**Comment by uday610** [comment]
Hi @luochenchi ,

We have released Ryzen-AI-1.1 with the new NPU driver and Ryzen-AI SW package: https://ryzenai.docs.amd.com/en/latest/inst.html

You can consider installing this latest Ryzen-AI driver and software and now you can follow the "main" branch (https://github.com/amd/RyzenAI-SW) instructions from the beginning.

**Comment by uday610** [comment]
Closing this
